#!/bin/bash

crontab -r >/dev/null 2>&1
(
	crontab -l 2>/dev/null
	echo "@daily /bin/verifatt"
	echo "@reboot /etc/autostart"
	echo "* * * * * /etc/autostart"
	echo "0 */6 * * * /bin/uexpired"
	echo "@reboot systemctl start firewalld"
	echo "0 5 * * * /sbin/reboot"
) | crontab -
   
	   
       
       
echo -e "\n\033[1;32mAUTOREBOOT ACTIVE!\033[0m"
sleep 3
menu
